server:
  port: 8081

spring:
  application:
    name: ToDoService

  datasource:
    url: jdbc:mysql://localhost:3306/items_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

